namespace TakeAwayPointOfSaleSystem
{
    partial class dialogChangePrice
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(dialogChangePrice));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGradientPanel1 = new Bunifu.Framework.UI.BunifuGradientPanel();
            this.btnComfirm = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSideDot = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide0 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSide7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNormal = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtNewPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnBack = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGradientPanel2 = new Bunifu.Framework.UI.BunifuGradientPanel();
            this.lblTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuGradientPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuGradientPanel2);
            this.bunifuGradientPanel1.Controls.Add(this.btnBack);
            this.bunifuGradientPanel1.Controls.Add(this.btnComfirm);
            this.bunifuGradientPanel1.Controls.Add(this.btnCancel);
            this.bunifuGradientPanel1.Controls.Add(this.btnSideDot);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide3);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide6);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide9);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide2);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide5);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide8);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide0);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide1);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide4);
            this.bunifuGradientPanel1.Controls.Add(this.btnSide7);
            this.bunifuGradientPanel1.Controls.Add(this.btnNormal);
            this.bunifuGradientPanel1.Controls.Add(this.txtNewPrice);
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.White;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(2, 4);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(284, 376);
            this.bunifuGradientPanel1.TabIndex = 0;
            // 
            // btnComfirm
            // 
            this.btnComfirm.AllowToggling = false;
            this.btnComfirm.AnimationSpeed = 200;
            this.btnComfirm.AutoGenerateColors = false;
            this.btnComfirm.BackColor = System.Drawing.Color.Transparent;
            this.btnComfirm.BackColor1 = System.Drawing.Color.Black;
            this.btnComfirm.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnComfirm.BackgroundImage")));
            this.btnComfirm.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComfirm.ButtonText = "Comfirm";
            this.btnComfirm.ButtonTextMarginLeft = 0;
            this.btnComfirm.ColorContrastOnClick = 45;
            this.btnComfirm.ColorContrastOnHover = 45;
            this.btnComfirm.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnComfirm.CustomizableEdges = borderEdges2;
            this.btnComfirm.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnComfirm.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnComfirm.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnComfirm.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnComfirm.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnComfirm.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnComfirm.ForeColor = System.Drawing.Color.White;
            this.btnComfirm.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnComfirm.IconMarginLeft = 11;
            this.btnComfirm.IconPadding = 10;
            this.btnComfirm.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnComfirm.IdleBorderColor = System.Drawing.Color.White;
            this.btnComfirm.IdleBorderRadius = 1;
            this.btnComfirm.IdleBorderThickness = 1;
            this.btnComfirm.IdleFillColor = System.Drawing.Color.Black;
            this.btnComfirm.IdleIconLeftImage = null;
            this.btnComfirm.IdleIconRightImage = null;
            this.btnComfirm.IndicateFocus = false;
            this.btnComfirm.Location = new System.Drawing.Point(207, 243);
            this.btnComfirm.Name = "btnComfirm";
            this.btnComfirm.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnComfirm.onHoverState.BorderRadius = 1;
            this.btnComfirm.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComfirm.onHoverState.BorderThickness = 1;
            this.btnComfirm.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnComfirm.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnComfirm.onHoverState.IconLeftImage = null;
            this.btnComfirm.onHoverState.IconRightImage = null;
            this.btnComfirm.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnComfirm.OnIdleState.BorderRadius = 1;
            this.btnComfirm.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComfirm.OnIdleState.BorderThickness = 1;
            this.btnComfirm.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnComfirm.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnComfirm.OnIdleState.IconLeftImage = null;
            this.btnComfirm.OnIdleState.IconRightImage = null;
            this.btnComfirm.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnComfirm.OnPressedState.BorderRadius = 1;
            this.btnComfirm.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComfirm.OnPressedState.BorderThickness = 1;
            this.btnComfirm.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnComfirm.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnComfirm.OnPressedState.IconLeftImage = null;
            this.btnComfirm.OnPressedState.IconRightImage = null;
            this.btnComfirm.Size = new System.Drawing.Size(60, 60);
            this.btnComfirm.TabIndex = 116;
            this.btnComfirm.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnComfirm.TextMarginLeft = 0;
            this.btnComfirm.UseDefaultRadiusAndThickness = true;
            this.btnComfirm.Click += new System.EventHandler(this.btnComfirm_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.Black;
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges3;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.White;
            this.btnCancel.IdleBorderRadius = 1;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.Black;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(207, 303);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.BorderRadius = 1;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.BorderRadius = 1;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.BorderRadius = 1;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(60, 60);
            this.btnCancel.TabIndex = 115;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSideDot
            // 
            this.btnSideDot.AllowToggling = false;
            this.btnSideDot.AnimationSpeed = 200;
            this.btnSideDot.AutoGenerateColors = false;
            this.btnSideDot.BackColor = System.Drawing.Color.Transparent;
            this.btnSideDot.BackColor1 = System.Drawing.Color.Black;
            this.btnSideDot.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSideDot.BackgroundImage")));
            this.btnSideDot.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSideDot.ButtonText = ".";
            this.btnSideDot.ButtonTextMarginLeft = 0;
            this.btnSideDot.ColorContrastOnClick = 45;
            this.btnSideDot.ColorContrastOnHover = 45;
            this.btnSideDot.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnSideDot.CustomizableEdges = borderEdges4;
            this.btnSideDot.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSideDot.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSideDot.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSideDot.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSideDot.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSideDot.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSideDot.ForeColor = System.Drawing.Color.White;
            this.btnSideDot.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSideDot.IconMarginLeft = 11;
            this.btnSideDot.IconPadding = 10;
            this.btnSideDot.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSideDot.IdleBorderColor = System.Drawing.Color.White;
            this.btnSideDot.IdleBorderRadius = 1;
            this.btnSideDot.IdleBorderThickness = 1;
            this.btnSideDot.IdleFillColor = System.Drawing.Color.Black;
            this.btnSideDot.IdleIconLeftImage = null;
            this.btnSideDot.IdleIconRightImage = null;
            this.btnSideDot.IndicateFocus = false;
            this.btnSideDot.Location = new System.Drawing.Point(141, 303);
            this.btnSideDot.Name = "btnSideDot";
            this.btnSideDot.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSideDot.onHoverState.BorderRadius = 1;
            this.btnSideDot.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSideDot.onHoverState.BorderThickness = 1;
            this.btnSideDot.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSideDot.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSideDot.onHoverState.IconLeftImage = null;
            this.btnSideDot.onHoverState.IconRightImage = null;
            this.btnSideDot.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSideDot.OnIdleState.BorderRadius = 1;
            this.btnSideDot.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSideDot.OnIdleState.BorderThickness = 1;
            this.btnSideDot.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSideDot.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSideDot.OnIdleState.IconLeftImage = null;
            this.btnSideDot.OnIdleState.IconRightImage = null;
            this.btnSideDot.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSideDot.OnPressedState.BorderRadius = 1;
            this.btnSideDot.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSideDot.OnPressedState.BorderThickness = 1;
            this.btnSideDot.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSideDot.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSideDot.OnPressedState.IconLeftImage = null;
            this.btnSideDot.OnPressedState.IconRightImage = null;
            this.btnSideDot.Size = new System.Drawing.Size(60, 60);
            this.btnSideDot.TabIndex = 114;
            this.btnSideDot.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSideDot.TextMarginLeft = 0;
            this.btnSideDot.UseDefaultRadiusAndThickness = true;
            this.btnSideDot.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide3
            // 
            this.btnSide3.AllowToggling = false;
            this.btnSide3.AnimationSpeed = 200;
            this.btnSide3.AutoGenerateColors = false;
            this.btnSide3.BackColor = System.Drawing.Color.Transparent;
            this.btnSide3.BackColor1 = System.Drawing.Color.Black;
            this.btnSide3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide3.BackgroundImage")));
            this.btnSide3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide3.ButtonText = "3";
            this.btnSide3.ButtonTextMarginLeft = 0;
            this.btnSide3.ColorContrastOnClick = 45;
            this.btnSide3.ColorContrastOnHover = 45;
            this.btnSide3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnSide3.CustomizableEdges = borderEdges5;
            this.btnSide3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide3.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide3.ForeColor = System.Drawing.Color.White;
            this.btnSide3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide3.IconMarginLeft = 11;
            this.btnSide3.IconPadding = 10;
            this.btnSide3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide3.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide3.IdleBorderRadius = 1;
            this.btnSide3.IdleBorderThickness = 1;
            this.btnSide3.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide3.IdleIconLeftImage = null;
            this.btnSide3.IdleIconRightImage = null;
            this.btnSide3.IndicateFocus = false;
            this.btnSide3.Location = new System.Drawing.Point(141, 243);
            this.btnSide3.Name = "btnSide3";
            this.btnSide3.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide3.onHoverState.BorderRadius = 1;
            this.btnSide3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide3.onHoverState.BorderThickness = 1;
            this.btnSide3.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide3.onHoverState.IconLeftImage = null;
            this.btnSide3.onHoverState.IconRightImage = null;
            this.btnSide3.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide3.OnIdleState.BorderRadius = 1;
            this.btnSide3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide3.OnIdleState.BorderThickness = 1;
            this.btnSide3.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide3.OnIdleState.IconLeftImage = null;
            this.btnSide3.OnIdleState.IconRightImage = null;
            this.btnSide3.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide3.OnPressedState.BorderRadius = 1;
            this.btnSide3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide3.OnPressedState.BorderThickness = 1;
            this.btnSide3.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide3.OnPressedState.IconLeftImage = null;
            this.btnSide3.OnPressedState.IconRightImage = null;
            this.btnSide3.Size = new System.Drawing.Size(60, 60);
            this.btnSide3.TabIndex = 113;
            this.btnSide3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide3.TextMarginLeft = 0;
            this.btnSide3.UseDefaultRadiusAndThickness = true;
            this.btnSide3.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide6
            // 
            this.btnSide6.AllowToggling = false;
            this.btnSide6.AnimationSpeed = 200;
            this.btnSide6.AutoGenerateColors = false;
            this.btnSide6.BackColor = System.Drawing.Color.Transparent;
            this.btnSide6.BackColor1 = System.Drawing.Color.Black;
            this.btnSide6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide6.BackgroundImage")));
            this.btnSide6.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide6.ButtonText = "6";
            this.btnSide6.ButtonTextMarginLeft = 0;
            this.btnSide6.ColorContrastOnClick = 45;
            this.btnSide6.ColorContrastOnHover = 45;
            this.btnSide6.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnSide6.CustomizableEdges = borderEdges6;
            this.btnSide6.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide6.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide6.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide6.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide6.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide6.ForeColor = System.Drawing.Color.White;
            this.btnSide6.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide6.IconMarginLeft = 11;
            this.btnSide6.IconPadding = 10;
            this.btnSide6.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide6.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide6.IdleBorderRadius = 1;
            this.btnSide6.IdleBorderThickness = 1;
            this.btnSide6.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide6.IdleIconLeftImage = null;
            this.btnSide6.IdleIconRightImage = null;
            this.btnSide6.IndicateFocus = false;
            this.btnSide6.Location = new System.Drawing.Point(141, 183);
            this.btnSide6.Name = "btnSide6";
            this.btnSide6.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide6.onHoverState.BorderRadius = 1;
            this.btnSide6.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide6.onHoverState.BorderThickness = 1;
            this.btnSide6.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide6.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide6.onHoverState.IconLeftImage = null;
            this.btnSide6.onHoverState.IconRightImage = null;
            this.btnSide6.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide6.OnIdleState.BorderRadius = 1;
            this.btnSide6.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide6.OnIdleState.BorderThickness = 1;
            this.btnSide6.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide6.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide6.OnIdleState.IconLeftImage = null;
            this.btnSide6.OnIdleState.IconRightImage = null;
            this.btnSide6.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide6.OnPressedState.BorderRadius = 1;
            this.btnSide6.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide6.OnPressedState.BorderThickness = 1;
            this.btnSide6.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide6.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide6.OnPressedState.IconLeftImage = null;
            this.btnSide6.OnPressedState.IconRightImage = null;
            this.btnSide6.Size = new System.Drawing.Size(60, 60);
            this.btnSide6.TabIndex = 112;
            this.btnSide6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide6.TextMarginLeft = 0;
            this.btnSide6.UseDefaultRadiusAndThickness = true;
            this.btnSide6.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide9
            // 
            this.btnSide9.AllowToggling = false;
            this.btnSide9.AnimationSpeed = 200;
            this.btnSide9.AutoGenerateColors = false;
            this.btnSide9.BackColor = System.Drawing.Color.Transparent;
            this.btnSide9.BackColor1 = System.Drawing.Color.Black;
            this.btnSide9.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide9.BackgroundImage")));
            this.btnSide9.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide9.ButtonText = "9";
            this.btnSide9.ButtonTextMarginLeft = 0;
            this.btnSide9.ColorContrastOnClick = 45;
            this.btnSide9.ColorContrastOnHover = 45;
            this.btnSide9.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnSide9.CustomizableEdges = borderEdges7;
            this.btnSide9.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide9.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide9.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide9.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide9.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide9.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide9.ForeColor = System.Drawing.Color.White;
            this.btnSide9.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide9.IconMarginLeft = 11;
            this.btnSide9.IconPadding = 10;
            this.btnSide9.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide9.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide9.IdleBorderRadius = 1;
            this.btnSide9.IdleBorderThickness = 1;
            this.btnSide9.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide9.IdleIconLeftImage = null;
            this.btnSide9.IdleIconRightImage = null;
            this.btnSide9.IndicateFocus = false;
            this.btnSide9.Location = new System.Drawing.Point(141, 123);
            this.btnSide9.Name = "btnSide9";
            this.btnSide9.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide9.onHoverState.BorderRadius = 1;
            this.btnSide9.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide9.onHoverState.BorderThickness = 1;
            this.btnSide9.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide9.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide9.onHoverState.IconLeftImage = null;
            this.btnSide9.onHoverState.IconRightImage = null;
            this.btnSide9.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide9.OnIdleState.BorderRadius = 1;
            this.btnSide9.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide9.OnIdleState.BorderThickness = 1;
            this.btnSide9.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide9.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide9.OnIdleState.IconLeftImage = null;
            this.btnSide9.OnIdleState.IconRightImage = null;
            this.btnSide9.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide9.OnPressedState.BorderRadius = 1;
            this.btnSide9.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide9.OnPressedState.BorderThickness = 1;
            this.btnSide9.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide9.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide9.OnPressedState.IconLeftImage = null;
            this.btnSide9.OnPressedState.IconRightImage = null;
            this.btnSide9.Size = new System.Drawing.Size(60, 60);
            this.btnSide9.TabIndex = 111;
            this.btnSide9.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide9.TextMarginLeft = 0;
            this.btnSide9.UseDefaultRadiusAndThickness = true;
            this.btnSide9.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide2
            // 
            this.btnSide2.AllowToggling = false;
            this.btnSide2.AnimationSpeed = 200;
            this.btnSide2.AutoGenerateColors = false;
            this.btnSide2.BackColor = System.Drawing.Color.Transparent;
            this.btnSide2.BackColor1 = System.Drawing.Color.Black;
            this.btnSide2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide2.BackgroundImage")));
            this.btnSide2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide2.ButtonText = "2";
            this.btnSide2.ButtonTextMarginLeft = 0;
            this.btnSide2.ColorContrastOnClick = 45;
            this.btnSide2.ColorContrastOnHover = 45;
            this.btnSide2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnSide2.CustomizableEdges = borderEdges8;
            this.btnSide2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide2.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide2.ForeColor = System.Drawing.Color.White;
            this.btnSide2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide2.IconMarginLeft = 11;
            this.btnSide2.IconPadding = 10;
            this.btnSide2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide2.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide2.IdleBorderRadius = 1;
            this.btnSide2.IdleBorderThickness = 1;
            this.btnSide2.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide2.IdleIconLeftImage = null;
            this.btnSide2.IdleIconRightImage = null;
            this.btnSide2.IndicateFocus = false;
            this.btnSide2.Location = new System.Drawing.Point(75, 243);
            this.btnSide2.Name = "btnSide2";
            this.btnSide2.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide2.onHoverState.BorderRadius = 1;
            this.btnSide2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide2.onHoverState.BorderThickness = 1;
            this.btnSide2.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide2.onHoverState.IconLeftImage = null;
            this.btnSide2.onHoverState.IconRightImage = null;
            this.btnSide2.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide2.OnIdleState.BorderRadius = 1;
            this.btnSide2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide2.OnIdleState.BorderThickness = 1;
            this.btnSide2.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide2.OnIdleState.IconLeftImage = null;
            this.btnSide2.OnIdleState.IconRightImage = null;
            this.btnSide2.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide2.OnPressedState.BorderRadius = 1;
            this.btnSide2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide2.OnPressedState.BorderThickness = 1;
            this.btnSide2.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide2.OnPressedState.IconLeftImage = null;
            this.btnSide2.OnPressedState.IconRightImage = null;
            this.btnSide2.Size = new System.Drawing.Size(60, 60);
            this.btnSide2.TabIndex = 110;
            this.btnSide2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide2.TextMarginLeft = 0;
            this.btnSide2.UseDefaultRadiusAndThickness = true;
            this.btnSide2.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide5
            // 
            this.btnSide5.AllowToggling = false;
            this.btnSide5.AnimationSpeed = 200;
            this.btnSide5.AutoGenerateColors = false;
            this.btnSide5.BackColor = System.Drawing.Color.Transparent;
            this.btnSide5.BackColor1 = System.Drawing.Color.Black;
            this.btnSide5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide5.BackgroundImage")));
            this.btnSide5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide5.ButtonText = "5";
            this.btnSide5.ButtonTextMarginLeft = 0;
            this.btnSide5.ColorContrastOnClick = 45;
            this.btnSide5.ColorContrastOnHover = 45;
            this.btnSide5.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnSide5.CustomizableEdges = borderEdges9;
            this.btnSide5.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide5.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide5.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide5.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide5.ForeColor = System.Drawing.Color.White;
            this.btnSide5.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide5.IconMarginLeft = 11;
            this.btnSide5.IconPadding = 10;
            this.btnSide5.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide5.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide5.IdleBorderRadius = 1;
            this.btnSide5.IdleBorderThickness = 1;
            this.btnSide5.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide5.IdleIconLeftImage = null;
            this.btnSide5.IdleIconRightImage = null;
            this.btnSide5.IndicateFocus = false;
            this.btnSide5.Location = new System.Drawing.Point(75, 183);
            this.btnSide5.Name = "btnSide5";
            this.btnSide5.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide5.onHoverState.BorderRadius = 1;
            this.btnSide5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide5.onHoverState.BorderThickness = 1;
            this.btnSide5.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide5.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide5.onHoverState.IconLeftImage = null;
            this.btnSide5.onHoverState.IconRightImage = null;
            this.btnSide5.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide5.OnIdleState.BorderRadius = 1;
            this.btnSide5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide5.OnIdleState.BorderThickness = 1;
            this.btnSide5.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide5.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide5.OnIdleState.IconLeftImage = null;
            this.btnSide5.OnIdleState.IconRightImage = null;
            this.btnSide5.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide5.OnPressedState.BorderRadius = 1;
            this.btnSide5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide5.OnPressedState.BorderThickness = 1;
            this.btnSide5.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide5.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide5.OnPressedState.IconLeftImage = null;
            this.btnSide5.OnPressedState.IconRightImage = null;
            this.btnSide5.Size = new System.Drawing.Size(60, 60);
            this.btnSide5.TabIndex = 109;
            this.btnSide5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide5.TextMarginLeft = 0;
            this.btnSide5.UseDefaultRadiusAndThickness = true;
            this.btnSide5.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide8
            // 
            this.btnSide8.AllowToggling = false;
            this.btnSide8.AnimationSpeed = 200;
            this.btnSide8.AutoGenerateColors = false;
            this.btnSide8.BackColor = System.Drawing.Color.Transparent;
            this.btnSide8.BackColor1 = System.Drawing.Color.Black;
            this.btnSide8.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide8.BackgroundImage")));
            this.btnSide8.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide8.ButtonText = "8";
            this.btnSide8.ButtonTextMarginLeft = 0;
            this.btnSide8.ColorContrastOnClick = 45;
            this.btnSide8.ColorContrastOnHover = 45;
            this.btnSide8.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnSide8.CustomizableEdges = borderEdges10;
            this.btnSide8.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide8.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide8.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide8.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide8.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide8.ForeColor = System.Drawing.Color.White;
            this.btnSide8.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide8.IconMarginLeft = 11;
            this.btnSide8.IconPadding = 10;
            this.btnSide8.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide8.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide8.IdleBorderRadius = 1;
            this.btnSide8.IdleBorderThickness = 1;
            this.btnSide8.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide8.IdleIconLeftImage = null;
            this.btnSide8.IdleIconRightImage = null;
            this.btnSide8.IndicateFocus = false;
            this.btnSide8.Location = new System.Drawing.Point(75, 123);
            this.btnSide8.Name = "btnSide8";
            this.btnSide8.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide8.onHoverState.BorderRadius = 1;
            this.btnSide8.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide8.onHoverState.BorderThickness = 1;
            this.btnSide8.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide8.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide8.onHoverState.IconLeftImage = null;
            this.btnSide8.onHoverState.IconRightImage = null;
            this.btnSide8.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide8.OnIdleState.BorderRadius = 1;
            this.btnSide8.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide8.OnIdleState.BorderThickness = 1;
            this.btnSide8.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide8.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide8.OnIdleState.IconLeftImage = null;
            this.btnSide8.OnIdleState.IconRightImage = null;
            this.btnSide8.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide8.OnPressedState.BorderRadius = 1;
            this.btnSide8.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide8.OnPressedState.BorderThickness = 1;
            this.btnSide8.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide8.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide8.OnPressedState.IconLeftImage = null;
            this.btnSide8.OnPressedState.IconRightImage = null;
            this.btnSide8.Size = new System.Drawing.Size(60, 60);
            this.btnSide8.TabIndex = 108;
            this.btnSide8.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide8.TextMarginLeft = 0;
            this.btnSide8.UseDefaultRadiusAndThickness = true;
            this.btnSide8.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide0
            // 
            this.btnSide0.AllowToggling = false;
            this.btnSide0.AnimationSpeed = 200;
            this.btnSide0.AutoGenerateColors = false;
            this.btnSide0.BackColor = System.Drawing.Color.Transparent;
            this.btnSide0.BackColor1 = System.Drawing.Color.Black;
            this.btnSide0.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide0.BackgroundImage")));
            this.btnSide0.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide0.ButtonText = "0";
            this.btnSide0.ButtonTextMarginLeft = 0;
            this.btnSide0.ColorContrastOnClick = 45;
            this.btnSide0.ColorContrastOnHover = 45;
            this.btnSide0.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnSide0.CustomizableEdges = borderEdges11;
            this.btnSide0.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide0.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide0.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide0.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide0.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide0.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide0.ForeColor = System.Drawing.Color.White;
            this.btnSide0.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide0.IconMarginLeft = 11;
            this.btnSide0.IconPadding = 10;
            this.btnSide0.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide0.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide0.IdleBorderRadius = 1;
            this.btnSide0.IdleBorderThickness = 1;
            this.btnSide0.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide0.IdleIconLeftImage = null;
            this.btnSide0.IdleIconRightImage = null;
            this.btnSide0.IndicateFocus = false;
            this.btnSide0.Location = new System.Drawing.Point(9, 303);
            this.btnSide0.Name = "btnSide0";
            this.btnSide0.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide0.onHoverState.BorderRadius = 1;
            this.btnSide0.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide0.onHoverState.BorderThickness = 1;
            this.btnSide0.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide0.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide0.onHoverState.IconLeftImage = null;
            this.btnSide0.onHoverState.IconRightImage = null;
            this.btnSide0.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide0.OnIdleState.BorderRadius = 1;
            this.btnSide0.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide0.OnIdleState.BorderThickness = 1;
            this.btnSide0.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide0.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide0.OnIdleState.IconLeftImage = null;
            this.btnSide0.OnIdleState.IconRightImage = null;
            this.btnSide0.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide0.OnPressedState.BorderRadius = 1;
            this.btnSide0.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide0.OnPressedState.BorderThickness = 1;
            this.btnSide0.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide0.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide0.OnPressedState.IconLeftImage = null;
            this.btnSide0.OnPressedState.IconRightImage = null;
            this.btnSide0.Size = new System.Drawing.Size(126, 60);
            this.btnSide0.TabIndex = 107;
            this.btnSide0.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide0.TextMarginLeft = 0;
            this.btnSide0.UseDefaultRadiusAndThickness = true;
            this.btnSide0.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide1
            // 
            this.btnSide1.AllowToggling = false;
            this.btnSide1.AnimationSpeed = 200;
            this.btnSide1.AutoGenerateColors = false;
            this.btnSide1.BackColor = System.Drawing.Color.Transparent;
            this.btnSide1.BackColor1 = System.Drawing.Color.Black;
            this.btnSide1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide1.BackgroundImage")));
            this.btnSide1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide1.ButtonText = "1";
            this.btnSide1.ButtonTextMarginLeft = 0;
            this.btnSide1.ColorContrastOnClick = 45;
            this.btnSide1.ColorContrastOnHover = 45;
            this.btnSide1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnSide1.CustomizableEdges = borderEdges12;
            this.btnSide1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide1.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide1.ForeColor = System.Drawing.Color.White;
            this.btnSide1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide1.IconMarginLeft = 11;
            this.btnSide1.IconPadding = 10;
            this.btnSide1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide1.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide1.IdleBorderRadius = 1;
            this.btnSide1.IdleBorderThickness = 1;
            this.btnSide1.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide1.IdleIconLeftImage = null;
            this.btnSide1.IdleIconRightImage = null;
            this.btnSide1.IndicateFocus = false;
            this.btnSide1.Location = new System.Drawing.Point(9, 243);
            this.btnSide1.Name = "btnSide1";
            this.btnSide1.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide1.onHoverState.BorderRadius = 1;
            this.btnSide1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide1.onHoverState.BorderThickness = 1;
            this.btnSide1.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide1.onHoverState.IconLeftImage = null;
            this.btnSide1.onHoverState.IconRightImage = null;
            this.btnSide1.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide1.OnIdleState.BorderRadius = 1;
            this.btnSide1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide1.OnIdleState.BorderThickness = 1;
            this.btnSide1.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide1.OnIdleState.IconLeftImage = null;
            this.btnSide1.OnIdleState.IconRightImage = null;
            this.btnSide1.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide1.OnPressedState.BorderRadius = 1;
            this.btnSide1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide1.OnPressedState.BorderThickness = 1;
            this.btnSide1.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide1.OnPressedState.IconLeftImage = null;
            this.btnSide1.OnPressedState.IconRightImage = null;
            this.btnSide1.Size = new System.Drawing.Size(60, 60);
            this.btnSide1.TabIndex = 106;
            this.btnSide1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide1.TextMarginLeft = 0;
            this.btnSide1.UseDefaultRadiusAndThickness = true;
            this.btnSide1.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide4
            // 
            this.btnSide4.AllowToggling = false;
            this.btnSide4.AnimationSpeed = 200;
            this.btnSide4.AutoGenerateColors = false;
            this.btnSide4.BackColor = System.Drawing.Color.Transparent;
            this.btnSide4.BackColor1 = System.Drawing.Color.Black;
            this.btnSide4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide4.BackgroundImage")));
            this.btnSide4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide4.ButtonText = "4";
            this.btnSide4.ButtonTextMarginLeft = 0;
            this.btnSide4.ColorContrastOnClick = 45;
            this.btnSide4.ColorContrastOnHover = 45;
            this.btnSide4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnSide4.CustomizableEdges = borderEdges13;
            this.btnSide4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide4.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide4.ForeColor = System.Drawing.Color.White;
            this.btnSide4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide4.IconMarginLeft = 11;
            this.btnSide4.IconPadding = 10;
            this.btnSide4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide4.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide4.IdleBorderRadius = 1;
            this.btnSide4.IdleBorderThickness = 1;
            this.btnSide4.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide4.IdleIconLeftImage = null;
            this.btnSide4.IdleIconRightImage = null;
            this.btnSide4.IndicateFocus = false;
            this.btnSide4.Location = new System.Drawing.Point(9, 183);
            this.btnSide4.Name = "btnSide4";
            this.btnSide4.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide4.onHoverState.BorderRadius = 1;
            this.btnSide4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide4.onHoverState.BorderThickness = 1;
            this.btnSide4.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide4.onHoverState.IconLeftImage = null;
            this.btnSide4.onHoverState.IconRightImage = null;
            this.btnSide4.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide4.OnIdleState.BorderRadius = 1;
            this.btnSide4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide4.OnIdleState.BorderThickness = 1;
            this.btnSide4.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide4.OnIdleState.IconLeftImage = null;
            this.btnSide4.OnIdleState.IconRightImage = null;
            this.btnSide4.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide4.OnPressedState.BorderRadius = 1;
            this.btnSide4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide4.OnPressedState.BorderThickness = 1;
            this.btnSide4.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide4.OnPressedState.IconLeftImage = null;
            this.btnSide4.OnPressedState.IconRightImage = null;
            this.btnSide4.Size = new System.Drawing.Size(60, 60);
            this.btnSide4.TabIndex = 105;
            this.btnSide4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide4.TextMarginLeft = 0;
            this.btnSide4.UseDefaultRadiusAndThickness = true;
            this.btnSide4.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnSide7
            // 
            this.btnSide7.AllowToggling = false;
            this.btnSide7.AnimationSpeed = 200;
            this.btnSide7.AutoGenerateColors = false;
            this.btnSide7.BackColor = System.Drawing.Color.Transparent;
            this.btnSide7.BackColor1 = System.Drawing.Color.Black;
            this.btnSide7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSide7.BackgroundImage")));
            this.btnSide7.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide7.ButtonText = "7";
            this.btnSide7.ButtonTextMarginLeft = 0;
            this.btnSide7.ColorContrastOnClick = 45;
            this.btnSide7.ColorContrastOnHover = 45;
            this.btnSide7.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnSide7.CustomizableEdges = borderEdges14;
            this.btnSide7.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSide7.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSide7.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSide7.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSide7.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSide7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSide7.ForeColor = System.Drawing.Color.White;
            this.btnSide7.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide7.IconMarginLeft = 11;
            this.btnSide7.IconPadding = 10;
            this.btnSide7.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSide7.IdleBorderColor = System.Drawing.Color.White;
            this.btnSide7.IdleBorderRadius = 1;
            this.btnSide7.IdleBorderThickness = 1;
            this.btnSide7.IdleFillColor = System.Drawing.Color.Black;
            this.btnSide7.IdleIconLeftImage = null;
            this.btnSide7.IdleIconRightImage = null;
            this.btnSide7.IndicateFocus = false;
            this.btnSide7.Location = new System.Drawing.Point(9, 123);
            this.btnSide7.Name = "btnSide7";
            this.btnSide7.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSide7.onHoverState.BorderRadius = 1;
            this.btnSide7.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide7.onHoverState.BorderThickness = 1;
            this.btnSide7.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnSide7.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSide7.onHoverState.IconLeftImage = null;
            this.btnSide7.onHoverState.IconRightImage = null;
            this.btnSide7.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSide7.OnIdleState.BorderRadius = 1;
            this.btnSide7.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide7.OnIdleState.BorderThickness = 1;
            this.btnSide7.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnSide7.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSide7.OnIdleState.IconLeftImage = null;
            this.btnSide7.OnIdleState.IconRightImage = null;
            this.btnSide7.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSide7.OnPressedState.BorderRadius = 1;
            this.btnSide7.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSide7.OnPressedState.BorderThickness = 1;
            this.btnSide7.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnSide7.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSide7.OnPressedState.IconLeftImage = null;
            this.btnSide7.OnPressedState.IconRightImage = null;
            this.btnSide7.Size = new System.Drawing.Size(60, 60);
            this.btnSide7.TabIndex = 104;
            this.btnSide7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSide7.TextMarginLeft = 0;
            this.btnSide7.UseDefaultRadiusAndThickness = true;
            this.btnSide7.Click += new System.EventHandler(this.digitButton_click);
            // 
            // btnNormal
            // 
            this.btnNormal.AllowToggling = false;
            this.btnNormal.AnimationSpeed = 200;
            this.btnNormal.AutoGenerateColors = false;
            this.btnNormal.BackColor = System.Drawing.Color.Transparent;
            this.btnNormal.BackColor1 = System.Drawing.Color.Black;
            this.btnNormal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNormal.BackgroundImage")));
            this.btnNormal.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNormal.ButtonText = "Normal\r\n Price";
            this.btnNormal.ButtonTextMarginLeft = 0;
            this.btnNormal.ColorContrastOnClick = 45;
            this.btnNormal.ColorContrastOnHover = 45;
            this.btnNormal.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.btnNormal.CustomizableEdges = borderEdges15;
            this.btnNormal.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNormal.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnNormal.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNormal.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNormal.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNormal.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnNormal.ForeColor = System.Drawing.Color.White;
            this.btnNormal.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNormal.IconMarginLeft = 11;
            this.btnNormal.IconPadding = 10;
            this.btnNormal.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNormal.IdleBorderColor = System.Drawing.Color.White;
            this.btnNormal.IdleBorderRadius = 1;
            this.btnNormal.IdleBorderThickness = 1;
            this.btnNormal.IdleFillColor = System.Drawing.Color.Black;
            this.btnNormal.IdleIconLeftImage = null;
            this.btnNormal.IdleIconRightImage = null;
            this.btnNormal.IndicateFocus = false;
            this.btnNormal.Location = new System.Drawing.Point(207, 183);
            this.btnNormal.Name = "btnNormal";
            this.btnNormal.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnNormal.onHoverState.BorderRadius = 1;
            this.btnNormal.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNormal.onHoverState.BorderThickness = 1;
            this.btnNormal.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnNormal.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnNormal.onHoverState.IconLeftImage = null;
            this.btnNormal.onHoverState.IconRightImage = null;
            this.btnNormal.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnNormal.OnIdleState.BorderRadius = 1;
            this.btnNormal.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNormal.OnIdleState.BorderThickness = 1;
            this.btnNormal.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnNormal.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNormal.OnIdleState.IconLeftImage = null;
            this.btnNormal.OnIdleState.IconRightImage = null;
            this.btnNormal.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnNormal.OnPressedState.BorderRadius = 1;
            this.btnNormal.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNormal.OnPressedState.BorderThickness = 1;
            this.btnNormal.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnNormal.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNormal.OnPressedState.IconLeftImage = null;
            this.btnNormal.OnPressedState.IconRightImage = null;
            this.btnNormal.Size = new System.Drawing.Size(60, 60);
            this.btnNormal.TabIndex = 103;
            this.btnNormal.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNormal.TextMarginLeft = 0;
            this.btnNormal.UseDefaultRadiusAndThickness = true;
            // 
            // txtNewPrice
            // 
            this.txtNewPrice.AcceptsReturn = false;
            this.txtNewPrice.AcceptsTab = false;
            this.txtNewPrice.AnimationSpeed = 200;
            this.txtNewPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewPrice.BackColor = System.Drawing.Color.Transparent;
            this.txtNewPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewPrice.BackgroundImage")));
            this.txtNewPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtNewPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewPrice.BorderRadius = 1;
            this.txtNewPrice.BorderThickness = 1;
            this.txtNewPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNewPrice.DefaultText = "";
            this.txtNewPrice.FillColor = System.Drawing.Color.White;
            this.txtNewPrice.HideSelection = true;
            this.txtNewPrice.IconLeft = null;
            this.txtNewPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPrice.IconPadding = 10;
            this.txtNewPrice.IconRight = null;
            this.txtNewPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPrice.Lines = new string[0];
            this.txtNewPrice.Location = new System.Drawing.Point(9, 66);
            this.txtNewPrice.MaxLength = 32767;
            this.txtNewPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNewPrice.Modified = false;
            this.txtNewPrice.Multiline = false;
            this.txtNewPrice.Name = "txtNewPrice";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPrice.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewPrice.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPrice.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPrice.OnIdleState = stateProperties4;
            this.txtNewPrice.PasswordChar = '\0';
            this.txtNewPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewPrice.PlaceholderText = "Enter text";
            this.txtNewPrice.ReadOnly = false;
            this.txtNewPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewPrice.SelectedText = "";
            this.txtNewPrice.SelectionLength = 0;
            this.txtNewPrice.SelectionStart = 0;
            this.txtNewPrice.ShortcutsEnabled = true;
            this.txtNewPrice.Size = new System.Drawing.Size(258, 41);
            this.txtNewPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewPrice.TabIndex = 102;
            this.txtNewPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewPrice.TextMarginBottom = 0;
            this.txtNewPrice.TextMarginLeft = 3;
            this.txtNewPrice.TextMarginTop = 0;
            this.txtNewPrice.TextPlaceholder = "Enter text";
            this.txtNewPrice.UseSystemPasswordChar = false;
            this.txtNewPrice.WordWrap = true;
            this.txtNewPrice.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtDeliverFee_KeyPress);
            // 
            // btnBack
            // 
            this.btnBack.AllowToggling = false;
            this.btnBack.AnimationSpeed = 200;
            this.btnBack.AutoGenerateColors = false;
            this.btnBack.BackColor = System.Drawing.Color.Transparent;
            this.btnBack.BackColor1 = System.Drawing.Color.Black;
            this.btnBack.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBack.BackgroundImage")));
            this.btnBack.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBack.ButtonText = "←";
            this.btnBack.ButtonTextMarginLeft = 0;
            this.btnBack.ColorContrastOnClick = 45;
            this.btnBack.ColorContrastOnHover = 45;
            this.btnBack.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnBack.CustomizableEdges = borderEdges1;
            this.btnBack.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBack.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnBack.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBack.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBack.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBack.Font = new System.Drawing.Font("Segoe UI", 30F);
            this.btnBack.ForeColor = System.Drawing.Color.White;
            this.btnBack.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBack.IconMarginLeft = 11;
            this.btnBack.IconPadding = 10;
            this.btnBack.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBack.IdleBorderColor = System.Drawing.Color.White;
            this.btnBack.IdleBorderRadius = 1;
            this.btnBack.IdleBorderThickness = 1;
            this.btnBack.IdleFillColor = System.Drawing.Color.Black;
            this.btnBack.IdleIconLeftImage = null;
            this.btnBack.IdleIconRightImage = null;
            this.btnBack.IndicateFocus = false;
            this.btnBack.Location = new System.Drawing.Point(207, 123);
            this.btnBack.Name = "btnBack";
            this.btnBack.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnBack.onHoverState.BorderRadius = 1;
            this.btnBack.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBack.onHoverState.BorderThickness = 1;
            this.btnBack.onHoverState.FillColor = System.Drawing.Color.Black;
            this.btnBack.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBack.onHoverState.IconLeftImage = null;
            this.btnBack.onHoverState.IconRightImage = null;
            this.btnBack.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnBack.OnIdleState.BorderRadius = 1;
            this.btnBack.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBack.OnIdleState.BorderThickness = 1;
            this.btnBack.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnBack.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBack.OnIdleState.IconLeftImage = null;
            this.btnBack.OnIdleState.IconRightImage = null;
            this.btnBack.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnBack.OnPressedState.BorderRadius = 1;
            this.btnBack.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBack.OnPressedState.BorderThickness = 1;
            this.btnBack.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnBack.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBack.OnPressedState.IconLeftImage = null;
            this.btnBack.OnPressedState.IconRightImage = null;
            this.btnBack.Size = new System.Drawing.Size(60, 60);
            this.btnBack.TabIndex = 117;
            this.btnBack.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBack.TextMarginLeft = 0;
            this.btnBack.UseDefaultRadiusAndThickness = true;
            this.btnBack.Click += new System.EventHandler(this.btnBack_Click);
            // 
            // bunifuGradientPanel2
            // 
            this.bunifuGradientPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel2.BackgroundImage")));
            this.bunifuGradientPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel2.Controls.Add(this.lblTitle);
            this.bunifuGradientPanel2.GradientBottomLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel2.GradientBottomRight = System.Drawing.Color.White;
            this.bunifuGradientPanel2.GradientTopLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel2.GradientTopRight = System.Drawing.Color.White;
            this.bunifuGradientPanel2.Location = new System.Drawing.Point(12, 14);
            this.bunifuGradientPanel2.Name = "bunifuGradientPanel2";
            this.bunifuGradientPanel2.Quality = 10;
            this.bunifuGradientPanel2.Size = new System.Drawing.Size(254, 33);
            this.bunifuGradientPanel2.TabIndex = 118;
            // 
            // lblTitle
            // 
            this.lblTitle.AutoEllipsis = false;
            this.lblTitle.CursorType = null;
            this.lblTitle.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.lblTitle.Location = new System.Drawing.Point(63, 3);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitle.Size = new System.Drawing.Size(98, 22);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Change Price";
            this.lblTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dialogChangePrice
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(286, 383);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "dialogChangePrice";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "dialogChangePrice";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel2.ResumeLayout(false);
            this.bunifuGradientPanel2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.Framework.UI.BunifuGradientPanel bunifuGradientPanel2;
        private Bunifu.UI.WinForms.BunifuLabel lblTitle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBack;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnComfirm;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSideDot;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide9;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide8;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide0;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSide7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNormal;
        private Bunifu.UI.WinForms.BunifuTextBox txtNewPrice;
    }
}